### ISSUE TITLE
Define /weather/historical/* endpoints, /weather/realtime endpoint

### ISSUE THREAD

**Issue by andyhaskell** [andyhaskell/climacell-go#1]
Currently, the only endpoints this client supports are `/weather/forecast/*` endpoints found in the [docs](https://www.climacell.co/weather-api/docs/), so this issue is to expand the Client type by defining:

- [ ] A `Client` method to contact the `/weather/historical/climacell` endpoint
- [ ] A `Client` method to contact the `/weather/historical/station` endpoint
- [ ] A `Client` method to contact the `/weather/realtime` endpoint

To the best of my knowledge, all of these endpoints use the `Weather` struct, or a slice of that struct, as. their 200 return. value, so we probably don't need to define any new types to complete this issue.

**Comment by grahhhhhhham** [comment]
Hey, saw you're post on dev.to and am hopping on board. Thought I'd throw it out that I'll be working on this issue in my spare time in the coming days. Might take a bit as I'll have to digest the current code structure (and am still learning Go) but will probably make headway on it this weekend!

**Comment by andyhaskell** [comment]
Closing this issue with https://github.com/andyhaskell/climacell-go/pull/9 merged
