### ISSUE TITLE
Add automated testing for the client

### ISSUE THREAD

**Issue by andyhaskell** [andyhaskell/climacell-go#3]
I think the best way to write this test coverage for each endpoint is:

- [x] Make a Go [httptest.Server](https://golang.org/pkg/net/http/httptest/#Server) serving the endpoint we're testing, by registering a net/http Handler that serves either a valid ClimaCell JSON response, or a ClimaCell error response
- [x] In the test case, set up a `Client` with a mock API key
- [x] Send requests, make assertions on the response's data that we got back the data we expected

**Comment by avivshafir** [comment]
add integration test for hourlyForecast in https://github.com/andyhaskell/climacell-go/pull/7

**Comment by andyhaskell** [comment]
Closing this with https://github.com/andyhaskell/climacell-go/pull/7 merged
